# Generated by Django 3.0.6 on 2020-09-14 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('user_email', models.EmailField(max_length=30, unique=True)),
                ('user_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='todolist_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_event', models.DateField()),
                ('event_name', models.CharField(max_length=30)),
                ('event_description', models.CharField(max_length=300)),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_registration')),
            ],
        ),
    ]
