# Generated by Django 3.0.6 on 2020-09-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist_info',
            name='date_event',
            field=models.CharField(max_length=11),
        ),
    ]
